### ISSUE TITLE
Ajustement des valeurs de Requests / Limits sur les POD des SE

### ISSUE THREAD

**Issue by gary-van-woerkens** [SocialGouv/support#338]
# Contexte

Les objectifs sont de: 
- Mieux consommer les ressources clusters déployé pour recevoir les produits des Startups
- réduire les coûts d'hébergement de la plateforme
- avoir les ressources appropriées sur les POD des startups déployés sur les environnements de dev et prod
- L'ajustement des requests est la première étape de l'amélioration 

# Todo

- [ ] Réaliser un tour des déploiements sur l'environnement de PROD pour lancer l'ajustement des ressources
- [ ] CPU request = 120% du CPU usage identifié sur les 30 derniers jours
- [ ] RAM request = 120% du RAM usage identifié sur les 30 derniers jours

# DOD
- l'usage des ressources des produits === 75% des requests
- ne pas avoir de pods sans requests

- TODO:
    - [ ] Faire en sorte que les environnements de review ne soient pas générés systématiquement
    - [ ] Trigger un workflow "waiting" qui pourra etre déclenché à la main depuis l'interface Github
    - [ ] Communiquer aupres des devs sur l'évolution de la CI dans ce sens
   

---

https://github.com/SocialGouv/serving-ml/blob/master/.kube-workflow/common/values.yaml

**Comment by devthejo** [comment]
concernant les env de review voici les travaux récent pour optimiser:
https://github.com/SocialGouv/kontinuous/blob/master/plugins/contrib/patches/20-minimize-dev-resources-requests.js
https://github.com/SocialGouv/kontinuous/blob/2d0be50b67875a883df3e17f7584adcd9b164f7a/plugins/fabrique/kontinuous.yaml#L26-L35

**Comment by devthejo** [comment]
plusieurs pistes:
- augmenter le nombre de pods par noeud
- réduire la taille des noeuds
- convention on demand review env, eg: branch naming dev/*

**Comment by igorrenquin** [comment]
> concernant l'optimisation de l'usage des ressources par les env de review, plusieurs actions possible:
> 
> * config du cluster kubernetes
>   
>   * augmenter le nombre de pods par noeud
>   * réduire la taille des noeuds
> * réduction des env de review:
>   
>   * actions:
>     
>     * convention on demand review env, eg: branch naming dev/*
>     * déclenchement manuel de l'action dans github
>   * études à réaliser:
>     

>     * sondage auprès des dev
>     * analyse du traffic sur les env de review

https://github.com/SocialGouv/support/issues/340

**Comment by igorrenquin** [comment]
Métriques qu'il est intéressant de visualiser:

- KPI 1 = Consommation CPU / Nb requêttes par plage de 1m sur une période de 24h
- Médiane = KPI 1 
- Delta = 95th percentile et la médiane

**Comment by devthejo** [comment]
ResourceReqCpuByPod = (MedianCpuByReq * MedianNumberOfSimultaneousReq) / MaxNumberOfSimultaneousMostIntensiveReq
  700m = 70m * 40 / 4

PodMargePercentage = 100 / CpuOfMostIntensiveReq * ResourceReqCpuByPod
  ~86% = 100 / 700m * 600m

HorizontalAutoscaleAtPercentage = 100 - PodMargePercentage
  14% = 100 - 86

IF HorizontalAutoscaleAtPercentage < 60%
  Force HorizontalAutoscaleAtPercentage = 60%
  et appliquer la formule réciproque
