### ISSUE TITLE
Les images `root`

### ISSUE THREAD

**Issue by gary-van-woerkens** [SocialGouv/support#341]
# Contexte

Les pentests réalisés sur la plateforme ont remonté qu'un certain nombre d'image s'exécutent avec les droits `root` sur les environnement.

Ces images peuvent permettre de compromettre par rebond aussi bien le cluster que les autres produits déployés

# Todo

- [x] exporter la liste des pod sur le cluster de prod (OPS)
- [x] identifier les containers types (SRE)
- [x] Mettre à jour la doc SRE sur les recommandations pour les images rootless cf:[issue 141](https://github.com/SocialGouv/support/issues/141) (SRE)
- [x] Mettre à disposition des SE les recommandations pour passer l'image Hasura et les autres (SRE)
- [x] communiquer auprès des SE sur les containers à corriger (OPS SRE)

# DOD
 - plus de containers de startups s'exécutant avec des process en `root` sur les clusters de dev et de prod

**Comment by gary-van-woerkens** [comment]
Etude faites au sujet des pods en ROOT:
https://github.com/SocialGouv/support/issues/141

**Comment by igorrenquin** [comment]
Hello la Team,

J'ai déposé sur [mattermost](https://mattermost.fabrique.social.gouv.fr/default/pl/pt6umrnjg78jje1mpmzsshkubh) la liste des containers tournant en `root` sur les clusters. 
Dans les résultats on vous a ajouté l'information sur la présence de `security context` sur le container.

`security context` est une autre façon d'exécuter le container en empéchant l'effet `root`

**Comment by revolunet** [comment]
je peux m'oqp de : 
 - [ ] metabase
 - [ ] serving-ml
 - [ ] template
 - [ ] dashlord-full

**Comment by gary-van-woerkens** [comment]
- [ ] @gary-van-woerkens  s'occupe de `carnets` 
- [ ] @maxgfr s'occupe de CDTN

**Comment by igorrenquin** [comment]
https://github.com/SocialGouv/support/issues/341#issuecomment-1369760204

- dashlord-full : corrigé (nginx)
- [X] serving-ml : corrigé avec le Dockerfile 
- metabase-* : ajout des securityContext

@revolunet il y a une seconde image utilisée par dashlord  alpine/git:v2.32.0 le user est `root`

**Comment by maxgfr** [comment]
@gary-van-woerkens normalement de notre côté, c'est bon

Hasura est en V2
