### ISSUE TITLE
Etudier comment augmenter la nombre de POD sur chaque noeuds

### ISSUE THREAD

**Issue by igorrenquin** [SocialGouv/support#345]
# Contexte

Actuellement les noeuds des clusters sont paramétrès pour recevoir 110 POD. 
Rarement les déploiements des Startups n'arrivent à consommer l'intégralité des ressources par contre le nombre de POD sur chaque noeuds est souvent atteint.

Pour améliorer le rendement de la plateforme il serait intéressant d'étudier comment faire pour modifier le paramétre et dans quelle limite il peut être ajusté.

# Todo

- [x] Etudier comment faire pour augmenter la limite de max pod sur un cluster
- [x] Etudier dans quelle limite on peut augmenter la limite max pod
- [x] Déployer le paramètre sur le cluster de DEV
# DOD
- Le scénario pour augmenter la valeur est identifiée
- La nouvelle limite de max pod est identifiée

**Comment by igorrenquin** [comment]
Le paramètre du `max pod` est définit lors du déploiement du cluster. Plus précisément au déploiement du `node pool`.
- actuellement le paramètre appliqué est de 110 PODs par noeud
- la valeur max du paramètre `max pod` est **250**

[AKS quotas and limits](https://learn.microsoft.com/en-us/azure/aks/quotas-skus-regions#service-quotas-and-limits)

Il est possible de modifier cette valeur en: 
- réinstallant le cluster
- déployant un nouveau node pool

**Comment by igorrenquin** [comment]
Go pour la création. d'un nouveau node pool sur le cluster de DEV.
max pod = **250**
