### ISSUE TITLE
Plan Migration OVH

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/support#429]
# Prérequis

 - [x] WIP kontinuous: utiliser le bon kubeconfig et le bon "extend" #424 #432
 - [x] startup-bootstrap : namespaces et storages #423
 - [x] Re-use des sealed-secrets sur les nouveaux clusters
 - [ ] Ouvrir accès aux PGs Azure depuis OVH
 - [x] Tooling CNPG : backups et sup grafana #426 #428
 - [x] Teleport CNPG #420 

```mermaid
gantt
    title Migration OVH
    dateFormat  DD-MM-YYYY
    section SRE
    Migration workloads DEV      :2023-07-15, 30d
    Migration Bdds                :2023-08-15, 45d
    Migration workloads PROD     :2023-10-01, 30d
```

D'autres infos sur Excel https://nextcloud.fabrique.social.gouv.fr/apps/onlyoffice/187252?filePath=%2FOPS%2FPlan-migration-vers-ovh.xlsx

**Comment by revolunet** [comment]
Priorisation et suivi migration : cf [suivi SE](https://docs.google.com/spreadsheets/d/1rk1fWiAoAAjJu1qrGMC2_SxCmFuq6A9Vk9aRBCADCgA/edit#gid=0)

1 - dev : SEs sans DBs ni storage
2 - dev:  SEs avec DBs / storage
3 - prod

**Comment by revolunet** [comment]
Modif de la stratégie suite délais homologation :
 - plus de migration OVH
 - focus tests CNPG + Azure

**Comment by octomir** [comment]
Reprise de la migration a partir du 25
